# Generated by Django 3.0 on 2019-06-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190523_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
