# Generated by Django 3.0 on 2019-06-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Email',
            field=models.EmailField(default=0, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Event_name',
            field=models.CharField(default=0, max_length=20, verbose_name='Event Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Name',
            field=models.CharField(default=0, max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='Phone'),
        ),
    ]
