# Generated by Django 3.0 on 2019-06-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190613_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
